### PR TITLE
New York Times article page clone

### PR DESCRIPTION
**Pull request by rocker-bell**
During this project, I learned and practiced and a new set of skills: positioning, Flexbox, CSS good practices, HTML good practices.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
### Status: Invalid Code Review Request :x: 

__Hi @Anasscodes, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reasons:__

- [ ] Some of your linter checks were not successful: to consider this project ready for review, you need to ensure that all GitHub Action Checks are running successfully. Kindly fix the linter errors.
- [ ] You should ensure that your PR has a descriptive title and summary. 
- [ ] You should also present a descriptive Readme for your project.


Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).
Do not forget to apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!


* * *
**Please, do not open a new Pull Request for subsequent reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * * 

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

**Comment by Anasscodes** [comment]
Hello,

Thank you for your reply i'll try my best to re-write the code regarding
the requirements.

**Review by smcommits — COMMENTED** [review]
# Status: Invalid :stop_sign: 
## Hello, @Anasscodes! Thank you so much for all the hard work. Your efforts are highly appreciated. Unfortunately, I can see that you still haven't addressed all the issues pointed out by the previous TSE. Your pull request has been marked as invalid due to the following reasons

- **Your PR message is not descriptive enough. Please write a summary of the changes you made in this PR.**
- **Your README is just a template. Please add all the necessary information relevant to your project**


Please take a step back and read a [lesson here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to learn more about making your repo professional. 

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

#### Note: As your code review request was invalidated, it does not count for the code review limit.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Anasscodes :wave: 

It's impressive to see how well you've done considering it's your first project at Microverse 👍 👏
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] You're expected to align elements on your webpage with a combination of all three techniques. ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)) but you've only made use of float and flex. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)).
* [ ] There's a scroll bar at the bottom of your page. You can set a max-width for your page to get rid of that.
* [ ] In the *`Theory of Inflation`* section, some of the corresponding text of the images are not well aligned and are also over-lapping.

Yours | Original
-- | --
image | image

##### Bottom part (section before the footer)

* [ ] Image previews on the leftmost side uses an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] Most popular articles on the rightmost side uses an anchor tag, any valid value e.g. "#" is okay for it's `href` attribute ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))



> ### "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Anasscodes :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
